#ansible-playbook global-playbook.yml --extra-vars "a=nginx b=present c=started"
---
- name: this is my first playbook
  hosts: all
  become: yes
  tasks:
    - name: install nginx software
      apt:
        name: "{{a}}"
        state: "{{b}}"
    - name: start the nginx service 
      service:
        name: "{{a}}"
        state: "{{c}}"
    - name: copy the index file
      copy:
        src: index.html
        dest: /var/www/html/index.html
         
