---
- name: this is my first playbook
  hosts: all
  become: yes
  tasks:
    - name: install nginx software
      apt:
        name: nginx
        state: present
    - name: start the nginx service 
      service:
        name: nginx
        state: started
    - name: copy the index file
      copy:
        src: index.html
        dest: /var/www/html/index.html
      notify: restart web server
    - name: uninstall tree
      apt:
        name: tree
        state: absent
    - name: copy andither file
      copy:
        src: index1.html
        dest: /var/www/html/index.html
      notify: restart web server


  handlers:
    - name: restart web server
      service:
        name: nginx
        state: restarted
         
