---
- name: call all child playbooks
  hosts: all
  become: yes
  tasks:
    - name: add child files
      include_tasks: "{{item}}"
      with_items:
        - inc-install.yml
        - inc-copy.yml
        - inc-start.yml
        - inc-restart.yml
